### ISSUE TITLE
Reacting to changes in mingleData / Reactive props

### ISSUE THREAD

**Issue by P-James** [ijpatricio/mingle#22]
Is there a way to get the vue to component to react to changes in `mingleData`?

I have a livewire event which my mingle component listens for with the `On` attribute. Then in the frontend I want the vue component to react to the changes.
Everything fires correctly except the final part of the Vue component receiving the new props.

Backend Livewire/ Mingle component: 
```php
<?php

namespace App\Livewire;

use Ijpatricio\Mingle\Concerns\InteractsWithMingles;
use Ijpatricio\Mingle\Contracts\HasMingles;
use Livewire\Attributes\On;
use Livewire\Component;

class SentencesList extends Component implements HasMingles
{
    use InteractsWithMingles;

    public string $message = 'Message in a bottle 🍾';

    public function component(): string
    {
        return 'resources/js/SentencesList.js';
    }

    public function mingleData(): array
    {
        ray('calling mingleData');
        ray($this->message);

        return [
            'message' => $this->message,
        ];
    }

    public function doubleIt($amount)
    {
        return $amount * 2;
    }

    #[On('sentences-list')]
    public function onSentencesList(string $message)
    {
        $this->message = $message;
        ray($this->message);
    }
}
```

and on the frontend:
```vue
<script setup>
import { onMounted, watch } from 'vue';

const $props = defineProps({
    wire: {},
    mingleData: {},
})

watch($props, (newprops, oldprops) => {
    console.log('props', newprops.mingleData, oldprops)
}, { deep: true, immediate: true })

onMounted(() => {
    console.log('onMounted', $props.mingleData)
})

</script>

<template>
    <div>
        {{ $props.mingleData.message }}
    </div>
</template>
```
those console logs are never triggered, apart from on the initial mount

**Comment by ijpatricio** [comment]
Hello @P-James

The mingleData never changes. It's loaded on initialization.

Livewire's paradigm of having reactive state for Server Side Rendering doesn't apply here, because we do the render in JS.

When we call server methods, we can pass the arguments directly, example: `$wire.doStuff(varA, varB)`

If we want to react to changes between JS/Livewire, we have to do it explicitly, being it state, or listening/emitting events.

We can use `$wire.on`, `$wire.dispatch` , `$wire.$set('property', value)`, Alpine's `$watch`, maybe `@entangle`...

Please explain the use case, so I can understand it, and better address it.

**Comment by ijpatricio** [comment]
I overlooked you just want to listen to the thing, because Mingle Data isn't supposed to be reactive. It could potentially cause a lot of ajax request and/or errors, depending on the app.

I now see what you mean.
What you want to do is to register a listener on component creation
We have `wire` in the props, so we can probably register the listener there:

```
wire.on('sentences-list', functionInVueComponent)
```

Let me know if this helps. I'll have a functional demo with this soon.

**Comment by ijpatricio** [comment]
I'm closing the issue, bc this solves it I think.
Let me know how it goes for you, or re-open if necessary. Thanks!

Ok, so check this out:

Files:
https://github.com/ijpatricio/mingle/blob/main/wrapper-mingle/app/Livewire/VueCounter.php
https://github.com/ijpatricio/mingle/blob/main/wrapper-mingle/resources/js/vue-counter/Counter.vue


VueCounter.php
```php
    public function doubleIt($amount)
    {
        $this->dispatch('doubleIt', randomString: Str::random(10));

        return $amount * 2;
    }
```

Counter.vue
```vue
props.wire.on('doubleIt', (randomString) => {
    console.log('Double it! 😎', randomString)
})
```

![image](https://github.com/user-attachments/assets/b9aa760e-1fc2-4836-8b4d-e2f37c01cf93)

**Comment by P-James** [comment]
Thanks @ijpatricio, that helps.
I think the confusion came from the 2 different mental models, and the fact I'm more familiar with Vue than Livewire.

**Comment by ijpatricio** [comment]
Yeah, it happens :)

Glad I could help!
