### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by andruu** [ijpatricio/mingle#4]
Getting the following when running `php artisan mingle:install`

![CleanShot 2024-04-15 at 14 49 36@2x](https://github.com/ijpatricio/mingle/assets/150730/fbcaf4c9-d07e-42a6-b0d8-a9d8f2b90874)

**Comment by ijpatricio** [comment]
Whoops. 

I should check if the view exists before trying to modify it.


The goal here is to add `@stack('scripts')` so that Mingle can inject the necessary code. See https://minglejs.unitedbycode.com/manual-instructions#layout-files

I'll change this. But before the package does it automatically, it's a simple step. Were you able to solve this locally?

Thanks

**Comment by andruu** [comment]
Yes using the manual instructions

**Comment by ijpatricio** [comment]
Fixed in https://github.com/ijpatricio/mingle/commit/0aacb22379fbf6f08b2043f1394e88f756c0bea9

Thank you, @andruu , for the feedback.
